//
//  StepperTesting.swift
//  SparkStepper
//
//  Created by louis.borlee on 29/11/2024.
//  Copyright © 2024 Adevinta. All rights reserved.
//

import Foundation

// TODO: remove this file if there is a file no generated by sourcery !

// IMPORTANT
// This file is needed because there is
// no code (without the code generated
// by sourcery) on this target.

